export const WORKFLOW_STAGE = {
  PARSE_SOURCE: "PARSE_SOURCE",
  EXTRACT_CANDIDATE: "EXTRACT_CANDIDATE",
  EXTRACT_JOB: "EXTRACT_JOB",
  DETECT_GAP: "DETECT_GAP",
  GENERATE_FOLLOW_UP: "GENERATE_FOLLOW_UP",
  REGENERATE_CANDIDATE: "REGENERATE_CANDIDATE",
  GENERATE_DRAFTS: "GENERATE_DRAFTS",
  GENERATE_INTERVIEW: "GENERATE_INTERVIEW",
  REWRITE_FOR_JOB: "REWRITE_FOR_JOB"
} as const;
